# Generated by Django 2.1.15 on 2024-04-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petadoption', '0002_cat_dog_rabbit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(upload_to='animal_images/'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(max_length=100),
        ),
    ]
