# Generated by Django 2.1.15 on 2024-04-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petadoption', '0003_auto_20240409_0317'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cat',
            new_name='Animals_List',
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
        migrations.DeleteModel(
            name='Rabbit',
        ),
    ]
